---

# - name: Download and unzip
#   include_role:
#     name: basic/download_and_unzip
#   vars:
#     pkg_conf: '{{ pkg_ic }}'

- name: Post install
  include: '{{ item_l1 }}'
  with_first_found:
  - files:
    - '{{ ansible_distribution }}.yml'
    - 'default.yml'
    paths: '{{ role_path }}/tasks/os_aware'
  loop_control:
    loop_var: item_l1