---

- name: Post install
  include: '{{ item_l1 }}'
  with_first_found:
  - files:
    - '{{ ansible_distribution }}.yml'
    - 'default.yml'
    paths: '{{ role_path }}/tasks/os_aware'
  loop_control:
    loop_var: item_l1