---

# - name: download and unzip
#   include_role:
#     name: basic/download_and_unzip
#   vars:
#     pkg_conf: '{{ pkg_ic }}'

- name: Install the dependence packages
  package: name="{{ item }}" state=present
  with_items: ['meld']

