---

- name: download and unzip
  include_role:
    name: basic/download_and_unzip
  vars:
    pkg_conf: '{{ pkg_ic }}'

- template:
    src: 'eclipse.desktop'
    dest: '~{{ dev_user}}/Desktop/eclipse.desktop'
    owner: '{{ dev_user}}'
    group: '{{ dev_group}}'
    mode: 0755
