---

- name: Download and unzip
  include_role:
    name: basic/download_and_unzip
  vars:
    pkg_conf: '{{ pkg_ic }}'

# export environment variable
- name: export GOROOT (/etc/environment)
  lineinfile:
    path: /etc/environment
    regexp: '^GOROOT='
    line: 'GOROOT={{ pkg_ic.install_path }}/{{ pkg_ic.basename }}'
- name: export GOROOT
  lineinfile:
    path: "{{ sys_profile }}"
    regexp: '^export GOROOT='
    line: 'export GOROOT={{ pkg_ic.install_path }}/{{ pkg_ic.basename }}'
- name: export GOROOT to PATH
  lineinfile:
    path: '{{ sys_profile }}'
    line: 'export PATH=$PATH:$GOROOT/bin'

# check
- name: check go installation
  raw: su - {{ dev_user}} -l -c "go version"
  register: pkg_v
  changed_when: False
  failed_when: "( pkg_v | failed ) or ( pkg_ic.version_expect not in pkg_v.stdout )"
