---

- include: "{{ item }}"
  with_first_found:
  - files:
    - '{{ ansible_distribution | lower }}.yml'
    - '{{ ansible_pkg_mgr | lower }}.yml'
    - 'default.yml'
    paths: '{{ role_path }}/tasks/pkg_aware'
    skip: true

- name: Check ansible versions
  raw: "ansible --version | grep ansible | grep -v config | cut -d ' ' -f2"
  # sudo: yes
  register: ansible_v
  failed_when: ( ansible_v | failed ) or ( ansible_v.stdout | version_compare('2.3.0.0', '<=') )
  changed_when: false

