---

- name: Install the software-properties-common packages
  package: name="{{ item }}" state=present
  with_items: ['software-properties-common']

- name: add-apt-repository
  apt_repository:
    repo: ppa:ansible/ansible
  when: ( ansible_distribution == "Ubuntu" )
  # failed_when: false
  # changed_when: false
  # ignore_errors: True

- name: Update repositories cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  failed_when: false
  changed_when: false
  ignore_errors: True

- name: Install the ansible packages
  package: name="{{ item }}" state=present
  with_items: ['ansible']

- name: Check ansible versions
  shell: "ansible --version | grep ansible | grep -v config | cut -d ' ' -f2"
  sudo: yes
  register: ansible_v
  failed_when: ( ansible_v | failed ) or ( ansible_v.stdout | version_compare('2.3.0.1', '<=') )

- debug: msg="ansible_v {{ ansible_v.stdout }}"