---

# install jdk files
- name: mkdir for jdk
  file: path="{{ jdk_dirname }}" state=directory
- name: upload jdk tar file
  copy:
    src: "{{ rcpath}}/{{ jdk_tar_filename }}"
    dest: "{{ jdk_dirname }}/{{ jdk_tar_filename }}"
- name: check unarchive jdk directory
  stat: path="{{ jdk_dirname }}/{{ jdk_basename }}"
  register: jdkfstat
- name: unarchive jdk
  unarchive:
    src: "{{ jdk_dirname }}/{{ jdk_tar_filename }}"
    dest: "{{ jdk_dirname }}"
    remote_src: yes
  when: jdkfstat.stat.isdir is not defined

# export environment variable
- name: export JAVA_HOME
  lineinfile:
    path: /etc/environment
    regexp: '^JAVA_HOME='
    line: 'JAVA_HOME={{ jdk_dirname }}/{{ jdk_basename }}'
- name: export JAVA_HOME (for RedHat)
  lineinfile:
    path: "{{ sys_profile }}"
    regexp: '^export JAVA_HOME='
    line: 'export JAVA_HOME={{ jdk_dirname }}/{{ jdk_basename }}'
#  when: ansible_os_family == "RedHat"
- name: export JAVA_HOME to PATH
  lineinfile:
    path: '{{ sys_profile }}'
    line: 'export PATH=$PATH:$JAVA_HOME/bin'
