---
jdk_dirname: /usr/lib/jdk

jdk_download_url: http://download.oracle.com/otn-pub/java/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/jdk-8u131-linux-x64.tar.gz
jdk_tar_filename: jdk-8u131-linux-x64.tar.gz
jdk_basename: jdk1.8.0_131
