---

- name: Create temporary deb file directory
  tempfile: state=directory
  register: deb_temp

- name: Download {{ pkg_ics.deb.file }}
  cached_get_url:
    cached: "{{ resource_cache }}/{{ pkg_ics.deb.file }}"
    url: "{{ pkg_ics.deb.url }}"
    dest: '{{ deb_temp.path }}/{{ pkg_ics.deb.file }}'

- name: Install a .deb package
  apt:
    deb: '{{ deb_temp.path}}/{{ pkg_ics.deb.file }}'