---

- name: Create temporary rpm file directory
  tempfile: state=directory
  register: rpm_temp

- name: Set temp_ic
  set_fact:
    temp_ic:
      name: '{{ pkg_ics.rpm.name}}'
      install_path: '{{ rpm_temp.path }}'
      url: "{{ pkg_ics.rpm.url }}"
      file: "{{ pkg_ics.rpm.file }}"

- name: get_url_with_cache
  cached_get_url:
    cached: '{{ resource_cache }}/{{ pkg_ics.rpm.file }}'
    url: "{{ pkg_ics.rpm.url }}"
    dest: '{{ rpm_temp.path }}/{{ pkg_ics.rpm.file }}'

- name: Install a .rpm package
  yum:
    name: '{{ rpm_temp.path}}/{{ temp_ic.file }}'
    state: present