---

- name: Install apps
  hosts: dev_machines
  become: yes
  become_method: sudo
  vars:
    # cluster_mode: false
    # fresh_unzip: false
    # drop_data: false
  vars_files:
    - ./vars/config.yml

  roles:
    - basic/system
    - basic/proxy
    - basic/sources
    - basic/common
    - basic/user
    - basic/firewall
    - text/vim
    - text/sublime
    - text/meld
    - internet/chrome
    - sharing/nfs
    - sharing/samba
    - sharing/vnc
    - dev/general

    - dev/lang/jdk
    - dev/lang/scala
    - dev/lang/golang
    - dev/lang/nodejs
    - dev/lang/python
    
    - dev/build/mvn
    - dev/build/gradle
    - dev/ide/eclipse
    - dev/ide/idea
    - dev/ansible
    - dev/docker

