# -*- mode: ruby -*-
# vi: set ft=ruby :

PRIVATE_KEY_SOURCE      = '/Users/gaoyuan/.vagrant.d/insecure_private_key'
PRIVATE_KEY_DESTINATION = '/home/vagrant/.ssh/id_rsa'

SUPPORTED_OS = {
  "centos-6"  => {box: "centos/6",            box_v: ""},
  "centos-7"  => {box: "centos/7",            box_v: ""},

  "ubuntu-12" => {box: "ubuntu/precise64",    box_v: ""}, #12
  "ubuntu-14" => {box: "ubuntu/trusty64",     box_v: ""},
  "ubuntu-16" => {box: "bento/ubuntu-16.04",  box_v: ""},
 
  "debian-7"  => {box: "debian/wheezy64",     box_v: ""}, #7
  "debian-8"  => {box: "debian/contrib-jessie64", box_v: ""}, 
}

$subnet = "192.168.101"
$num_instances = 7
$vm_memory = 1024
$vm_cpus = 2
$instance_name_prefix = "devnode"

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box_check_update = false

  oses = [
    "centos-6",
    "centos-7",

    "ubuntu-12",
    "ubuntu-14",
    "ubuntu-16",
   
    "debian-7",
    "debian-8",
  ]

  max_id = $num_instances - 1
  (0..max_id).each do |i|
    ip = 100 + i
    config.vm.define node_name = "%s-%02d" % [$instance_name_prefix, i] do |node|
      node.vm.hostname = node_name

      os = SUPPORTED_OS[oses[i % oses.length]]
      node.vm.box = os[:box]
      if os.has_key? :box_v
        node.vm.box_version = os[:box_v]
      end

      node.vm.network "private_network" , ip: "#{$subnet}.#{ip}"
      node.vm.provider "virtualbox" do |v|
        v.name = node_name
        v.cpus = $vm_cpus
        v.memory = $vm_memory
      end
      # copy private key so hosts can ssh using key authentication (the script below sets permissions to 600)
      node.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "host_id_rsa.pub"
      node.vm.provision "shell", path: "bootstrap.sh"
    end
  end
end
