---

# Prepare file location
- name: mkdir for python
  file: path="{{ python_dirname }}" state=directory
  changed_when: False

- name: fetch python2 version
  shell: "python2 --version 2>&1"
  register: python2_v
  changed_when: False
- name: install python2
  include: install_by_make.yml
  when: "( python2_v | failed ) or ( python2_version_expect not in python2_v.stdout )"
  vars:
    python_x: python2
    python_tar_filename: '{{ python2_tar_filename }}'
    python_basename: '{{ python2_basename}}'
    python_v_expect: '{{ python2_version_expect}}'

- name: fetch python3 version
  shell: "python3 --version 2>&1"
  register: python3_v
  changed_when: False
- name: install python3
  include: install_by_make.yml
  when: "( python3_v | failed ) or ( python3_version_expect not in python3_v.stdout )"
  vars:
    python_x: python3
    python_tar_filename: '{{ python3_tar_filename }}'
    python_basename: '{{ python3_basename}}'
    python_v_expect: '{{ python3_version_expect}}'

# - include: install_from_tar.yml
