---

- name: download and unzip
  include_role:
    name: basic/download_and_unzip
  vars:
    pkg_conf: '{{ pkg_ic }}'


# make install
- name: make install
  shell: |
    ./configure
    make
    make install
  args:
    chdir: "{{ pkg_ic.install_path }}/{{ pkg_ic.basename}}"

- name: check python installation
  shell: "{{ python_x}} --version 2>&1"
  register: python_v
  changed_when: False
  failed_when: "( python_v | failed ) or ( python_v_expect not in python_v.stdout )"

