---

- name: Download and unzip
  include_role:
    name: basic/download_and_unzip
  vars:
    pkg_conf: '{{ pkg_ic }}'

# make install
- name: Make install
  shell: |
    ./configure
    make
    make install
  args:
    chdir: "{{ pkg_ic.install_path }}/{{ pkg_ic.basename}}"

- name: Check python installation
  raw: su - {{ dev_user}} -l -c "{{ python_x}} --version 2>&1"
  # next line wont work on centos ?
  # shell: "{{ python_x}} --version 2>&1"
  register: python_v
  changed_when: False
  failed_when: "( python_v | failed ) or ( (pkg_ic.version_expect not in python_v.stdout ) and (ansible_python_version not in python_v.stdout ) )"

