---

- name: download and unzip
  include_role:
    name: basic/download_and_unzip
  vars:
    pkg_conf: '{{ pkg_ic }}'

# export environment variable
- name: export SCALA_HOME (/etc/environment)
  lineinfile:
    path: /etc/environment
    regexp: '^SCALA_HOME='
    line: 'SCALA_HOME={{ pkg_ic.install_path }}/{{ pkg_ic.basename }}'
- name: export SCALA_HOME
  lineinfile:
    path: "{{ sys_profile }}"
    regexp: '^export SCALA_HOME='
    line: 'export SCALA_HOME={{ pkg_ic.install_path }}/{{ pkg_ic.basename }}'
- name: export SCALA_HOME to PATH
  lineinfile:
    path: '{{ sys_profile }}'
    line: 'export PATH=$PATH:$SCALA_HOME/bin'

# check
- name: check scala installation
  raw: su - {{ dev_user}} -l -c "scala -version"
  register: pkg_v
  failed_when: "( pkg_v | failed ) or ( pkg_ic.version_expect not in pkg_v.stdout) "
  changed_when: false
