---


- name: Download and unzip
  include_role:
    name: basic/download_and_unzip
  vars:
    pkg_conf: '{{ pkg_ic }}'

# export environment variable
- name: export SBT_HOME (/etc/environment)
  lineinfile:
    path: /etc/environment
    regexp: '^SBT_HOME='
    line: 'SBT_HOME={{ pkg_ic.install_path }}/{{ pkg_ic.basename }}'
- name: export SBT_HOME
  lineinfile:
    path: "{{ sys_profile }}"
    regexp: '^export SBT_HOME='
    line: 'export SBT_HOME={{ pkg_ic.install_path }}/{{ pkg_ic.basename }}'
- name: export SBT_HOME to PATH
  lineinfile:
    path: '{{ sys_profile }}'
    line: 'export PATH=$PATH:$SBT_HOME/bin'

# check
- name: check sbt installation
  raw: su - {{ dev_user}} -l -c "sbt sbt-version"
  register: pkg_v
  failed_when: "( pkg_v | failed ) or ( pkg_ic.version_expect not in pkg_v.stdout) "
  changed_when: false
