---

# check
- name: Check sbt installation
  raw: su - {{ dev_user}} -l -c "sbt sbtVersion"
  register: pkg_v
  changed_when: false
  ignore_errors: true
- name: Print version
  debug:
    msg: "Expect: {{ pkg_ic.version_expect }}, got: {{ pkg_v.stdout }}"

- name: Do installation
  include_tasks: do_install_sbt_from_tar.yml
  when: ( pkg_v | failed ) or ( pkg_ic.version_expect not in pkg_v.stdout)