---

# check
- name: Check scala installation
  shell: /bin/bash -l -c "{{ pkg_ic.version_command }}"
  register: pkg_v
  changed_when: false
  ignore_errors: true
- name: Print version
  debug:
    msg: "Expect: {{ pkg_ic.version_expect }}, got: {{ pkg_v.stdout }}"

- name: Do installation
  include_tasks: do_install_scala_from_tar.yml
  when: ( pkg_v | failed ) or ( pkg_ic.version_expect not in pkg_v.stdout)