---

# install scala files
- name: mkdir for scala
  file: path="{{ scala_dirname }}" state=directory
- name: upload scala tar file
  copy:
    src: "{{ rcpath}}/{{ scala_tar_filename }}"
    dest: "{{ scala_dirname }}/{{ scala_tar_filename }}"
- name: check unarchive scala directory
  stat: path="{{ scala_dirname }}/{{ scala_basename }}"
  register: scalafstat
- name: unarchive scala
  unarchive:
    src: "{{ scala_dirname }}/{{ scala_tar_filename }}"
    dest: "{{ scala_dirname }}"
    remote_src: yes
  when: scalafstat.stat.isdir is not defined

# export environment variable
- name: export SCALA_HOME (/etc/environment)
  lineinfile:
    path: /etc/environment
    regexp: '^SCALA_HOME='
    line: 'SCALA_HOME={{ scala_dirname }}/{{ scala_basename }}'
- name: export SCALA_HOME
  lineinfile:
    path: "{{ sys_profile }}"
    regexp: '^export SCALA_HOME='
    line: 'export SCALA_HOME={{ scala_dirname }}/{{ scala_basename }}'
#  when: ansible_os_family == "RedHat"
- name: export SCALA_HOME to PATH
  lineinfile:
    path: '{{ sys_profile }}'
    line: 'export PATH=$PATH:$SCALA_HOME/bin'

# check
- name: check if scala installed
  raw: su - {{ dev_user}} -l -c "scala -version"
  register: command_result
  failed_when: "( command_result | failed ) or ( scala_version_expect not in command_result.stdout) "
  changed_when: false
