---

- name: Install sbt from tar
  include_tasks: install_sbt_from_tar.yml
  vars:
    pkg_ic: '{{ pkg_ics.sbt_ic}}'

- name: Install scala from repo
  include_tasks: install_scala_from_tar.yml
  vars:
    pkg_ic: '{{ pkg_ics.scala_ic}}'
