---

# Uninstall old versions
- name: remove old version
  apt:
    name: '{{ item }}'
    state: absent
  with_items: [docker, docker-engine, docker.io]

# Recommended extra packages for Trusty 14.04
- name: Update repositories cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  failed_when: false
  changed_when: false
  ignore_errors: True
- name: extra packages for trusty
  raw: apt-get install linux-image-extra-$(uname -r) linux-image-extra-virtual
  when: ( ansible_distribution == "Ubuntu" ) and ( ansible_distribution_release == "trusty")

# Install Docker CE
- name: Update repositories cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  failed_when: false
  changed_when: false
  ignore_errors: True
- name: install dependencies
  apt:
    name: '{{ item }}'
  with_items: [apt-transport-https, ca-certificates, curl, software-properties-common]
- apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present
- name: add-apt-repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release }}  stable"
- name: Update repositories cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  failed_when: false
  changed_when: false
  ignore_errors: True
- name: install docker-ce
  apt:
    name: '{{ item }}'
  with_items: [docker-ce]



