---

# Manage Docker as a non-root user (affect after logout and logback, try "$ docker run hello-world")
- name: Present docker group, (manage docker as no-root user)
  group: name='{{ docker_group }}' state=present
- name: Add user to docker group, (manage docker as no-root user)
  user:
    name: "{{ dev_user }}"
    groups: '{{ docker_group }}'
    append: yes

- name: Configure Docker to start on boot
  service: name=docker enabled=yes state=started

- name: Configure Docker daemon
  template: src=daemon.json dest=/etc/docker/daemon.json
# - file:
#     path: '/etc/systemd/system/docker.service.d'
#     state: directory
#     owner: root
#     group: root
#     mode: 0755
# - template: src=http-proxy.conf dest=/etc/systemd/system/docker.service.d/http-proxy.conf

# https://stackoverflow.com/questions/26550360/docker-ubuntu-behind-proxy
- name: Export PROXIES
  blockinfile:
    path: '/etc/default/docker'
    marker: "# {mark} PROXY BLOCK"
    block: |
      export http_proxy={{ '"' }}{{ proxy.http }}{{ '"' }}
      export https_proxy={{ '"' }}{{ proxy.https }}{{ '"' }}
      export ftp_proxy={{ '"' }}{{ proxy.ftp }}{{ '"' }}
      export socks_proxy={{ '"' }}{{ proxy.socks }}{{ '"' }}
      export no_proxy={{ '"' }}{{ proxy.no_proxy }}{{ '"' }}
  when: proxy.enable

- name: Restart docker daemon
  service: name=docker state=restarted enabled=yes
- set_fact:
    docker_installed: true

