---

# Manage Docker as a non-root user (affect after logout and logback, try "$ docker run hello-world")
- name: Present docker group, (manage docker as no-root user)
  group: name='{{ docker_group }}' state=present
- name: Add user to docker group, (manage docker as no-root user)
  user:
    name: "{{ dev_user }}"
    groups: '{{ docker_group }}'
    append: yes

# Configure Docker to start on boot
- name: Configure Docker to start on boot
  service: name=docker enabled=yes state=started

- name: Configure Docker daemon
  template: src=daemon.json dest=/etc/docker/daemon.json

# https://stackoverflow.com/questions/26550360/docker-ubuntu-behind-proxy
- name: Configure Docker proxy
  file:
    path: '/etc/systemd/system/docker.service.d'
    state: directory
    owner: root
    group: root
    mode: 0755
- name: Configure Docker proxy
  template: src=http-proxy.conf dest=/etc/systemd/system/docker.service.d/http-proxy.conf
  when: proxy.enable

- name: Docker daemon reload
  systemd:
    state: restarted
    daemon_reload: yes
    name: docker
- name: Restart docker daemon
  service: name=docker state=restarted enabled=yes
