---

- blockinfile:
    path: /etc/environment
    marker: "# {mark} PROXY BLOCK"
    block: |
      http_proxy={{ '"' }}{{ proxy.http }}{{ '"' }}
      https_proxy={{ '"' }}{{ proxy.https }}{{ '"' }}
      ftp_proxy={{ '"' }}{{ proxy.ftp }}{{ '"' }}
      socks_proxy={{ '"' }}{{ proxy.socks }}{{ '"' }}
      no_proxy={{ '"' }}{{ proxy.no_proxy }}{{ '"' }}
      HTTP_PROXY={{ '"' }}{{ proxy.http }}{{ '"' }}
      HTTPS_PROXY={{ '"' }}{{ proxy.https }}{{ '"' }}
      FTP_PROXY={{ '"' }}{{ proxy.ftp }}{{ '"' }}
      SOCKS_PROXY={{ '"' }}{{ proxy.socks }}{{ '"' }}
      NO_PROXY={{ '"' }}{{ proxy.no_proxy }}{{ '"' }}
  when: proxy.enable

- name: export PROXIES
  blockinfile:
    path: '{{ sys_bashrc }}'
    marker: "# {mark} PROXY BLOCK"
    block: |
      export http_proxy={{ '"' }}{{ proxy.http }}{{ '"' }}
      export https_proxy={{ '"' }}{{ proxy.https }}{{ '"' }}
      export ftp_proxy={{ '"' }}{{ proxy.ftp }}{{ '"' }}
      export socks_proxy={{ '"' }}{{ proxy.socks }}{{ '"' }}
      export no_proxy={{ '"' }}{{ proxy.no_proxy }}{{ '"' }}
  when: proxy.enable

- blockinfile:
    path: /etc/apt/apt.conf.d/95proxies
    marker: "// {mark} PROXY BLOCK"
    block: |
      Acquire::http::proxy {{ '"' }}{{ proxy.http }}{{ '"' }};
      Acquire::https::proxy {{ '"' }}{{ proxy.https }}{{ '"' }};
      Acquire::ftp::proxy {{ '"' }}{{ proxy.ftp }}{{ '"' }};
      Acquire::socks::proxy {{ '"' }}{{ proxy.socks }}{{ '"' }};
    create: yes
  when: proxy.enable
