---

- name: Export proxies
  env_edit:
    marker: "# {mark} PROXY BLOCK"
    profile_filename: proxy.sh
    varlist:
      - http_proxy: '{{ proxy.http }}'
      - HTTP_PROXY: '{{ proxy.http }}'
      - https_proxy: '{{ proxy.https }}'
      - HTTPS_PROXY: '{{ proxy.https }}'
      - ftp_proxy: '{{ proxy.ftp }}'
      - FTP_PROXY: '{{ proxy.ftp }}'
      - socks_proxy: '{{ proxy.socks }}'
      - SOCKS_PROXY: '{{ proxy.socks }}'
      - no_proxy: '{{ proxy.no_proxy }}'
      - NO_PROXY: '{{ proxy.no_proxy }}'
  when: proxy.enable

- name: Un-Export proxies
  env_edit:
    marker: "# {mark} PROXY BLOCK"
    profile_filename: proxy.sh
    state: absent
  when: not proxy.enable

- name: Platform dependent setting
  include_tasks: "{{ item }}"
  with_first_found:
  - files:
    - '{{ ansible_distribution_release }}.yml'
    - '{{ ansible_distribution }}.yml'
    - '{{ ansible_os_family }}.yml'
    - '{{ ansible_pkg_mgr }}.yml'
    - 'default.yml'
    paths: '{{ role_path }}/tasks/os_aware'
    skip: true
