---

- name: Fetch JAVA_HOME, setup if absent
  command: /bin/sh -l -c "echo $JAVA_HOME"
  register: fetch_java_home
  changed_when: false

- debug: msg="os{{ ':'}}{{ ansible_os_family }}, distribution{{ ':'}}{{ ansible_distribution }}-{{ ansible_distribution_version }}({{ ansible_distribution_release }}), JAVA_HOME{{ ':'}}{{ fetch_java_home.stdout }}"
- name: Fetch java version
  raw: su - {{ dev_user}} -l -c "java -version" 
  register: java_v
  changed_when: false
  ignore_errors: true
- name: Print Java version
  debug:
    msg: "{{ java_v.stdout }}"

- name: Install JDK
  block:
    - name: Install from repo
      include_tasks: install_from_repo.yml
      when: pkg_ic.repo_install
    - name: Install from tar
      include_tasks: install_from_tar.yml

    - name: Check java installation
      raw: su - {{ dev_user}} -l -c "java -version" 
      register: java_v
      changed_when: false
      failed_when: "( java_v | failed )"
    - name: Print Java version
      debug:
        msg: "{{ java_v.stdout }}"
  when: ((fetch_java_home.stdout == '') or ( java_v | failed ) ) 
