---

- name: mkdir resource directory
  file: path="{{ role_path }}/{{ rcpath}}" state=directory

- debug: msg="{{ docker_packages }}"
# - name: check if jdk_tar_file exist
#   stat: path="{{ role_path }}/{{ rcpath}}/{{ jdk_tar_filename }}"
#   register: jdktarfstat
