---

- include_vars: '{{ item }}'
  with_first_found:
  - files:
    - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
    - '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'
    - '{{ ansible_distribution }}.yml'
    - '{{ ansible_os_family }}.yml'
    - '{{ ansible_pkg_mgr }}.yml'
    - 'default.yml'
    paths: '{{ role_path }}/vars/os'

- name: Install the dependence packages
  package: name="{{ item }}" state=present
  with_items: '{{ pkg_set.dependencies }}'

- name: Present nfs sharing dir
  file:
    path: '{{ sharing_dir }}'
    owner: '{{ nobody }}'
    group: '{{ nogroup }}'
    state: directory
    mode: 0777
- name: Present sample file
  file:
    path: '{{ sharing_dir }}/{{ inventory_hostname }}'
    owner: '{{ nobody }}'
    group: '{{ nogroup }}'
    state: touch
    mode: 0666

- name: Define exports
  blockinfile:
    path: /etc/exports
    block: |
      {{ sharing_dir }}    *(rw,sync,no_root_squash,no_subtree_check)

- name: Restart nfsserver
  service: name='{{ pkg_set.service }}' state=restarted enabled=yes

- name: Check nfs setting
  raw: "exportfs"
  register: exportfs_o
  failed_when: ( exportfs_o | failed ) or ( sharing_dir not in exportfs_o.stdout )
  changed_when: false


