---

resource_cache: "{{ playbook_dir | dirname }}/.resources"

dev_group: developer
dev_user: andy
dev_user_pwd: passw0rd

sharing_dir: /workzone
smb_conf:
  sharing_dir: /workzone_smb
  init_pwd: aabbcc
# http_proxy: 
vnc_init_pwd: aabbcc

proxy:
  enable: false
  default: http://192.168.3.2:1080
  http: http://192.168.3.2:1080
  https: http://192.168.3.2:1080
  ftp: http://192.168.3.2:1080
  socks: http://192.168.3.2:1080
  no_proxy: "localhost,127.0.0.1,localaddress,.localdomain.com"

mounts:
  - {type: nfs, host: localhost, path: /workzone, mountpoint: /xxx}