---

- include_vars: '{{ item }}'
  with_first_found:
  - files:
      - '{{ ansible_distribution | lower }}-{{ ansible_distribution_release | lower }}.yml'
      - '{{ ansible_distribution | lower }}.yml'
      - '{{ ansible_os_family | lower }}.yml'
      - 'default.yml'
    paths: '{{ role_path }}/vars/os'

- name: Install the dependence packages
  package: name="{{ item }}" state=present
  with_items: '{{ pkg_set.dependencies }}'

- file:
    path: '{{ smb_sharing_dir }}'
    owner: '{{ nobody }}'
    group: '{{ nogroup }}'
    state: directory
    mode: 0777
- file:
    path: '{{ smb_sharing_dir }}/{{ inventory_hostname}}'
    owner: '{{ nobody }}'
    group: '{{ nogroup }}'
    state: touch
    mode: 0666

- template:
    src: smb.conf.v4
    dest: /etc/samba/smb.conf
    backup: yes

- name: restart samba service
  service: name={{ item }} state=started enabled=yes
  with_items: '{{ pkg_set.services }}'
