---

- name: Setup proxy for apt
  blockinfile:
    path: /etc/apt/apt.conf.d/95proxies
    marker: "// {mark} PROXY BLOCK"
    block: |
      Acquire::http::proxy {{ '"' }}{{ proxy.http }}{{ '"' }};
      Acquire::https::proxy {{ '"' }}{{ proxy.https }}{{ '"' }};
      Acquire::ftp::proxy {{ '"' }}{{ proxy.ftp }}{{ '"' }};
      Acquire::socks::proxy {{ '"' }}{{ proxy.socks }}{{ '"' }};
    create: yes
