---

- name: Check if sources.list.bk exist
  stat: path="/etc/apt/sources.list.bk"
  register: bkstat
- name: Backup sources.list
  copy:
    remote_src: true
    src: /etc/apt/sources.list
    dest: /etc/apt/sources.list.bk
  when: ( not bkstat.stat.exists )

- name: Use new repo setting
  template:
    src: '{{ ansible_distribution | lower }}/{{ ansible_distribution_release | lower}}.sources.list'
    dest: /etc/apt/sources.list

- name: Update repo cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  failed_when: false
  changed_when: false
  ignore_errors: True

# - name: apt-get upgrade
#   raw: apt-get upgrade -y
