---

- name: mkdir resource directory
  file: path="{{ role_path }}/{{ rcpath}}" state=directory

# Prepare idea resource
- name: check if idea_tar_file exist
  stat: path="{{ role_path }}/{{ rcpath}}/{{ idea_tar_filename }}"
  register: ideatarfstat
- fail:
    msg: "Please download manually. (https://www.jetbrains.com/idea/)"
  when: not ideatarfstat.stat.exists
