---

- name: download and unzip
  include_role:
    name: basic/download_and_unzip
  vars:
    pkg_conf: '{{ pkg_ic }}'

- file:
    src: '{{ pkg_ic.install_path}}/{{ pkg_ic.basename}}'
    dest: '~{{ dev_user}}/Desktop/{{ pkg_ic.basename}}'
    state: link
# - name: setup
#   shell:
#     ./idea.sh
#     chdir: '{{ idea_install_path}}/{{ idea_basename}}/bin'

# - template:
#     src: 'idea.desktop'
#     dest: '~{{ dev_user}}/Desktop/idea.desktop'
#     owner: '{{ dev_user}}'
#     group: '{{ dev_group}}'
#     mode: 0755
