---

- name: create temporary deb file directory
  tempfile: state=directory
  register: deb_temp

- set_fact:
    temp_ic:
      name: docker
      install_path: '{{ deb_temp.path }}'
      url: "{{ docker_packages[ansible_distribution | lower ][ansible_distribution_release].url }}"
      file: "{{ docker_packages[ansible_distribution | lower ][ansible_distribution_release].file }}"

- name: download and unzip
  include_role:
    name: basic/download_and_unzip
  vars:
    do_unzip: false
    pkg_conf: '{{ temp_ic }}'

- name: Install a .deb package
  apt:
    deb: '{{ deb_temp.path}}/{{ temp_ic.file }}'
