---
python_dirname: /tmp/python

python2_download_url: https://www.python.org/ftp/python/2.7.13/Python-2.7.13.tgz
python2_tar_filename: Python-2.7.13.tgz
python2_basename: Python-2.7.13
python2_version_expect: 'Python 2.7.13'

python3_download_url: https://www.python.org/ftp/python/3.6.2/Python-3.6.2.tgz
python3_tar_filename: Python-3.6.2.tgz
python3_basename: Python-3.6.2
python3_version_expect: 'Python 3.6.2'
