---

- include_vars: '{{ item }}'
  with_first_found:
  - files:
      - '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}{{ python_suffix }}.yml'
      - '{{ ansible_os_family }}-{{ ansible_distribution_major_version }}{{ python_suffix }}.yml'
      - '{{ ansible_distribution }}{{ python_suffix }}.yml'
      - '{{ ansible_os_family }}{{ python_suffix }}.yml'
      - '{{ ansible_os_family }}.yml'
      - 'default{{ python_suffix }}.yml'
      - 'default.yml'
    paths: '{{ role_path }}/vars/os'

- name: Install the dependence packages
  package: name="{{ item }}" state=present
  with_items: '{{ dependency }}'

# - name: set proxy for git
#   shell: |
#     git config --global http.proxy {{ proxy.http }}
#     git config --global https.proxy {{ proxy.https }}
#   when: (proxy.enable)
#   become: true
#   become_method: sudo
#   become_user: '{{ dev_user }}'
