---

- include: "{{ item }}"
  with_first_found:
  - files:
    - '{{ ansible_distribution | lower }}.yml'
    - '{{ ansible_pkg_mgr | lower }}.yml'
    - 'default.yml'
    paths: '{{ role_path }}/tasks/pkg_aware'
    skip: true
