---

- name: Load proper tasks
  include: "{{ item }}"
  with_first_found:
  - files:
    - '{{ ansible_distribution }}.yml'
    - '{{ ansible_pkg_mgr }}.yml'
    - 'default.yml'
    paths: '{{ role_path }}/tasks/os_aware'
  static: no
